version: "3.9"

services:
  application:
    container_name: application
    build: .
    ports:
      - "4000:4000"
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "cd frontend && npm install && cd ../backend && npm install && cd .. && npm run start-app"
    networks:
      - default
  database:
    container_name: database
    image: postgres
    ports:
      - '5432:5432'
    environment:
      DB_HOST: database
      POSTGRES_DB: 'tea-coffee-db'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default: